name: Copy File to Public Repo

on: push

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Push Private files
        uses: dobbelina/multi_file_bandit@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.CUSTOM_TOKEN }}
        with:
          source_file: "README.md,README_zh_CN.md,icon.png,preview.png,plugin.json"
          destination_repo: "wetoria/sy-plugin-enhance"
          user_email: "bot@wetoria.me"
          user_name: "GithubActions"
          commit_message: "copy private file to public"
